// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyyxlspffoiegbcpluwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5eXhsc3BmZm9pZWdiY3BsdXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzQwODUsImV4cCI6MjA2NjQ1MDA4NX0.jt-CWJqh6EpZqzSk2D-XJsaxVps3w8aPT4QPE9YEBVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);